Downloading (…)lve/main/config.json: 100%|██████████| 480/480 [00:00<00:00, 244kB/s]
Downloading (…)olve/main/vocab.json: 100%|██████████| 899k/899k [00:00<00:00, 2.34MB/s]
Downloading (…)olve/main/merges.txt: 100%|██████████| 456k/456k [00:00<00:00, 1.51MB/s]
Downloading (…)/main/tokenizer.json: 100%|██████████| 1.36M/1.36M [00:00<00:00, 2.98MB/s]






Downloading (…)"pytorch_model.bin";: 100%|██████████| 331M/331M [00:10<00:00, 30.7MB/s]
Traceback (most recent call last):
  File "/home/daviddu/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 717, in convert_to_tensors
    tensor = as_tensor(value)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/daviddu/Documents/EC_C147/MBTIPredictor/train_bert_mlm.py", line 31, in <module>
    input_encoding = tokenizer(
  File "/home/daviddu/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2523, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/daviddu/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2609, in _call_one
    return self.batch_encode_plus(
  File "/home/daviddu/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2800, in batch_encode_plus
    return self._batch_encode_plus(
  File "/home/daviddu/miniconda3/lib/python3.10/site-packages/transformers/models/roberta/tokenization_roberta_fast.py", line 263, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/home/daviddu/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 477, in _batch_encode_plus
    return BatchEncoding(sanitized_tokens, sanitized_encodings, tensor_type=return_tensors)
  File "/home/daviddu/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 210, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/home/daviddu/miniconda3/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 733, in convert_to_tensors
    raise ValueError(
